name: Working dir and sells
on: [push]

jobs:
  display-info:
    runs-on: ubuntu-latest
    steps:
      - name: Display working dir and list files
        run: |
          pwd
          ls -al
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
  display-info-w:
    runs-on: windows-latest
    steps:
      - name: Display working dir and list files
        run: |
          pwd
          ls -al
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
